stages:
  generate-train-data:
    cmd: python -W ignore -m src.data_creation --validation=False --dataset="synthetic"
    deps:
    - src/data_creation.py
    params:
    - data_creation
    outs:
    - data/train/synthetic/raw
  
  generate-val-data:
    foreach: ${datasets.val}
    do:
      cmd: python -W ignore -m src.data_creation --validation=True --dataset=${item.name}
      deps:
      - src/data_creation.py
      params:
      - data_creation
      outs:
      - data/val/${item.name}/raw

  process-val-data:
    foreach: ${datasets.val}
    cmd: python -W ignore -m src.data_processing --validation=True --dataset=${item.name}
    deps:
    - src/data_processing.py
    - data/val/${item.name}/raw
    params:
    - model
    - data_creation
    outs:
    - data/val/${item.name}/processed

  process-train-data:
    cmd: python -W ignore -m src.data_processing
    deps:
    - src/data_processing.py
    - data/raw
    params:
      - model
      - data_creation
    outs:
    - data/processed

  training:
    cmd: python -W ignore -m src.training
    deps:
    - src/training.py
    - data/processed
    params:
    - training
    - model
    - model_name
    outs:
    - models/latest.pth

  validation:
    cmd: python -W ignore -m src.validation
    deps:
    - src/validation.py
    - data/processed
    - models/latest.pth
    params:
    - model
    - model_name
    metrics:
    - reports/latest.json

  visualisation:
    frozen: false
    cmd: python -W ignore -m src.visualization
    deps:
    - src/visualization.py
    - data/processed
    - models/latest.pth
    params:
    - model
    - visualization
    outs:
    - figures
