stages:
  data-creation:
    cmd: python -W ignore -m src.data_creation
    deps:
    - src/data_creation.py
    params:
    - params.json:
      - data_creation
    outs:
    - data/raw

  data-processing:
    cmd: python -W ignore -m src.data_processing
    deps:
    - src/data_processing.py
    - data/raw
    params:
    - params.json:
      - model
      - data_creation
    outs:
    - data/processed

  training:
    cmd: python -W ignore -m src.training
    deps:
    - src/training.py
    - data/processed
    params:
    - params.json:
      - training
      - model
    outs:
    - models/latest.pth

  validation:
    cmd: python -W ignore -m src.validation
    deps:
    - src/validation.py
    - data/processed
    - models/latest.pth
    params:
    - params.json:
      - model
    metrics:
    - reports/latest.json

  visualisation:
    cmd: python -W ignore -m src.visualization
    deps:
    - src/visualization.py
    - data/processed
    - models/latest.pth
    params:
    - params.json:
      - model
      - visualization
    outs:
    - figures
  