stages:
  generate-training-data:
    cmd: python -W ignore -m src.data_creation --dataset="synthetic"
    deps:
    - src/data_creation.py
    params:
    - data_creation
    outs:
    - data/training/synthetic/raw
  
  generate-validation-data:
    foreach: ${datasets.validation}
    do:
      cmd: python -W ignore -m src.data_creation --validation --dataset=${item}
      deps:
      - src/data_creation.py
      params:
      - data_creation
      outs:
      - data/validation/${item}/raw

  process-validation-data:
    foreach: ${datasets.validation}
    do:
      cmd: python -W ignore -m src.data_processing --validation --dataset=${item}
      deps:
      - src/data_processing.py
      - data/validation/${item}/raw
      params:
      - model
      - data_creation
      outs:
      - data/validation/${item}/processed

  process-training-data:
    cmd: python -W ignore -m src.data_processing
    deps:
    - src/data_processing.py
    - data/training/synthetic/raw
    params:
      - model
      - data_creation
    outs:
    - data/training/synthetic/processed

  training:
    cmd: python -W ignore -m src.training
    deps:
    - src/training.py
    - data/training/synthetic/processed
    params:
    - training
    - model
    outs:
    - models/latest.pth

  validation:
    foreach: ${datasets.validation}
    do:
      cmd: python -W ignore -m src.validation --dataset=${item}
      deps:
      - src/validation.py
      - data/validation/${item}/processed
      - src/visualization.py
      - models/latest.pth
      params:
      - model
      - model_name

  visualization:
    foreach: ${datasets.visualization}
    do:
      cmd: python -W ignore -m src.visualization --dataset=${item}
      deps:
      - src/visualization.py
      - data/validation/${item}/processed
      - models/latest.pth
      params:
      - model
      - model_name
      - visualization

  unsupervised:
    foreach: ${datasets.validation}
    do:
      cmd: python -W ignore -m src.unsupervised --dataset=${item}
      deps:
      - src/validation.py
      - src/unsupervised.py
      - data/validation/${item}/raw
